### ISSUE TITLE
Scan option does not appear on survey pages

### ISSUE THREAD

**Issue by inks007** [Unisante/Barcode-Scanner#1]
Hi Team Unisanté,

Can you please enable the scan option on survey pages?

A QRCode scanner external module does this, with source code here:
https://github.com/jrdevgit/REDCap-QRScanner/blob/master/QRScanner.php

Thank you.

**Comment by RaveeFazal** [comment]
I've run into this issue as well, please update this thread with a fix if available.

**Comment by unisante-user** [comment]
[1.1.0](https://github.com/Unisante/Barcode-Scanner/releases/tag/1.1.0) release introduces the functionality to scan on the survey pages
